import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BlueHolding Gamified LMS Solution",
  description: "Generated by create next app",
  icons : {
    icon : ".favicon.svg",
  }
};

export default function RootLayout({ children }) {
  return (
        <html lang="en">
        <body>
          {/* <Header/> */}
          <main>{children}</main>
          <Footer/>
        </body>
      </html>
  );
}
